[{
    "company_name":"apple",
    "date":ISODate("2020-09-25"),
    "students_appeared":"bharath,hariniy,dharanish,kural,nandha"
},
{
    "company_name":"microsoft",
    "date":ISODate("2020-10-16"),
    "students_appeared":"deepak,vignesh,hasan,jai,nagaraj"
},
{
    "company_name":"zoho",
    "date":ISODate("2020-10-27"),
    "students_appeared":"kholi,aswin,rohit,siraj,padithar"
},
{
    "company_name":"guvi",
    "date":ISODate("2020-11-15"),
    "students_appeared":"priya,hasifa,yoga,ramya,barani"
},
{
    "company_name":"hcl",
    "date":ISODate("2020-11-25"),
    "students_appeared":"jithesh,sanjay,kamal,aishwar,josiya"
}]